CatalogoDeProjetos/Models/ErrorViewModel.cs
namespace CatalogoDeProjetos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CatalogoDeProjetos/Models/FavoriteRepositoryModel.cs
namespace CatalogoDeProjetos.Models
{
    public class FavoriteRepositoryModel
    {
        public int Id { get; set; }
        public string RepositoryId { get; set; }
    }
}

CatalogoDeProjetos/Models/RepositoriosModel.cs
using System.ComponentModel.DataAnnotations;

namespace CatalogoDeProjetos.Models
{
    public class RepositoriosModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do repositorio")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite a descrição")]
        public string Descricao { get; set; }
        [Required(ErrorMessage = "Digite a linguagem")]
        public string Linguagem { get; set; }
        [Required(ErrorMessage = "Digite o nome do dono do repositorio")]
        public string Dono { get; set; }
        [Required(ErrorMessage = "informe a data da ultima atualização")]
        public DateTime? DataAtualizacao { get; set; }

        public bool Favorito { get; set; }
    }
}

CatalogoDeProjetos/Controllers/HomeController.cs
using CatalogoDeProjetos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CatalogoDeProjetos.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CatalogoDeProjetos/Controllers/RepositoriosController.cs
using CatalogoDeProjetos.Models;
using CatalogoDeProjetos.Repository;
using Microsoft.AspNetCore.Mvc;

namespace CatalogoDeProjetos.Controllers
{
    public class RepositoriosController : Controller
    {
        private readonly IRepository _repositorio;

        public IActionResult Detalhes(int id)
        {
            RepositoriosModel repositorio = _repositorio.ListarPorId(id);
            return View(repositorio);
        }


        public RepositoriosController(IRepository repositorio)
        {
            _repositorio = repositorio;
        }
        public IActionResult Index()
        {
            List<RepositoriosModel> repositorio = _repositorio.BuscarTodos();
            return View(repositorio);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            RepositoriosModel repositorio = _repositorio.ListarPorId(id);
            return View(repositorio);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            _repositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        public IActionResult Apagar(int id)
        {
            

            RepositoriosModel repositorio = _repositorio.ListarPorId(id);
            return View(repositorio);
        }

        public IActionResult ApagarTodos()
        {
            _repositorio.ExcluirTodos();
            TempData["MensagemSucesso"] = "Todos os repositórios foram excluídos.";
            return RedirectToAction("Index");
        }



        [HttpPost]
        public IActionResult Criar(RepositoriosModel repositorio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.Adicionar(repositorio);
                    //   TempData["MensagemSucesso"] = "Contato cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                // }*/

                return View(repositorio);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, erro ao cadastrar contato. Erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(RepositoriosModel repositorio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.Atualizar(repositorio);
                    TempData["MensagemSucesso"] = "Contato editado com sucesso";
                    return RedirectToAction("Index");
                }
                return View("Editar", repositorio);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, erro ao editar contato. Erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Favoritar(int id)
        {
            RepositoriosModel repositorio = _repositorio.ListarPorId(id);
            repositorio.Favorito = true;
            _repositorio.Atualizar(repositorio);
            return RedirectToAction("Detalhes", new { id = id });
        }

        public IActionResult Desfavoritar(int id)
        {
            RepositoriosModel repositorio = _repositorio.ListarPorId(id);
            repositorio.Favorito = false;
            _repositorio.Atualizar(repositorio);
            return RedirectToAction("Detalhes", new { id = id });
        }

        public IActionResult Favoritos()
        {
            List<RepositoriosModel> repositoriosFavoritos = _repositorio.BuscarTodos().Where(r => r.Favorito).ToList();
            return View("Index", repositoriosFavoritos);
        }
    }
  


}

CatalogoDeProjetos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo</h1>
    ´<p>Sistema de controle para catalogar projetos KRIA Tecnologia</p>
</div>

CatalogoDeProjetos/Views/Repositorios/Apagar.cshtml
@model RepositoriosModel
@{
    ViewData["Title"] = "Confirmação apagar repositorio";
}
<div class="text-center">
    <h3>Realmente deseja apagar o repositorio (@Model.Nome)</h3>
    <a class="btn btn-primary btn-block" role="button" asp-controller="Repositorios" asp-action="Index">Cancelar exclusão</a>
    <a class="btn btn-danger btn-block" role="button" asp-controller="Repositorios" asp-action="ApagarConfirmacao" asp-route-id="@Model.Id">Confirmar exclusão</a>
</div>

CatalogoDeProjetos/Views/Repositorios/Criar.cshtml
@model RepositoriosModel
@{
    ViewData["Title"] = "criar repositorio";
}
<div class="text-center">

    <h1 class="display-4">Cadastrar repositorio</h1>

</div>
<form asp-controller="Repositorios" asp-action="Criar" method="post">
    <div class="mb-3">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do repositorio">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="mb-3">
        <label for="descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Digite a Descricao">
        @Html.ValidationMessageFor(x => x.Descricao)
    </div>

    <div class="mb-3">
        <label for="linguagem">Linguagem</label>
        <input type="text" asp-for="Linguagem" class="form-control" placeholder="Digite a Linguagem">
        @Html.ValidationMessageFor(x => x.Linguagem)
    </div>

     <div class="mb-3">
        <label for="linguagem">Data de atualização</label>
        <input type="date" asp-for="DataAtualizacao" class="form-control" placeholder="Digite a Data de atualização">
        @Html.ValidationMessageFor(x => x.DataAtualizacao)
    </div>


    <div class="mb-3">
        <label for="dono">Dono do repositorio</label>
        <input type="text" asp-for="Dono" class="form-control" placeholder="Digite o Dono do repositorio">
        @Html.ValidationMessageFor(x => x.Dono)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Repositorios" asp-action="Index" role="button">Voltar</a>
</form>

CatalogoDeProjetos/Views/Repositorios/Detalhes.cshtml
@model RepositoriosModel
@{
    ViewData["Title"] = "Detalhes do Repositório";
}

<h1>@Model.Nome</h1>
<table class="table">
    <tbody>
        <tr>
            <th>Id</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>Nome</th>
            <td>@Model.Nome</td>
        </tr>
        <tr>
            <th>Descrição</th>
            <td>@Model.Descricao</td>
        </tr>
        <tr>
            <th>Linguagem</th>
            <td>@Model.Linguagem</td>
        </tr>
        <tr>
            <th>Data de Atualização</th>
            <td>@Model.DataAtualizacao</td>
        </tr>
        <tr>
            <th>Dono</th>
            <td>@Model.Dono</td>
        </tr>
        @if (Model.Favorito)
        {
        <form asp-action="Desfavoritar" asp-route-id="@Model.Id">
            <button type="submit" class="btn btn-danger">Remover dos favoritos</button>
        </form>
        }
        else
        {
        <form asp-action="Favoritar" asp-route-id="@Model.Id">
    <button type="submit" class="btn btn-primary">Adicionar aos favoritos</button>
        </form>
        }
    </tbody>
</table>

<div class="text-center">
    <div class="a-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Repositorios" asp-action="Editar" asp-route-id="@Model.Id">Editar</a>
        <a class="btn btn-danger" role="button" asp-controller="Repositorios" asp-action="Apagar" asp-route-id="@Model.Id">Excluir</a>
        <a class="btn btn-secondary" role="button" asp-controller="Repositorios" asp-action="Index" asp-route-id="@Model.Id">Voltar</a>
        
    </div>
</div>

CatalogoDeProjetos/Views/Repositorios/Editar.cshtml
@model RepositoriosModel
@{
    ViewData["Title"] = "editar repositorio";
}

<div class="text-center">

    <h1 class="display-4">Editar repositorio</h1>

</div>
<form asp-controller="Repositorios" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="mb-3">
        <label for="descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Digite a Descricao">
        @Html.ValidationMessageFor(x => x.Descricao)
    </div>

    <div class="mb-3">
        <label for="linguagem">Linguagem</label>
        <input type="text" asp-for="Linguagem" class="form-control" placeholder="Digite a Linguagem">
        @Html.ValidationMessageFor(x => x.Linguagem)
    </div>


    <div class="mb-3">
        <label for="linguagem">Data de atualização</label>
        <input type="date" asp-for="DataAtualizacao" class="form-control" placeholder="Digite a Data de atualização">
        @Html.ValidationMessageFor(x => x.DataAtualizacao)
    </div>

     <div class="mb-3">
        <label for="dono">Dono do repositorio</label>
        <input type="text" asp-for="Dono" class="form-control" placeholder="Digite o Dono do repositorio">
        @Html.ValidationMessageFor(x => x.Dono)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Repositorios" asp-action="Index" role="button">Voltar</a>
</form>

CatalogoDeProjetos/Views/Repositorios/Index.cshtml
@model List<RepositoriosModel>
@{
    ViewData["Title"] = "Meus repositorios";
}

<div class="text-center">
    <div class="a-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Repositorios" asp-action="Criar">Adicionar novo repositorio</a>
        <a class="btn btn-success" role="button" asp-action="Favoritos">Meus favoritos</a>
        <button class="btn btn-danger" onclick="confirmDelete()">Excluir todos os repositórios</button>

    </div>

   

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
            @TempData["MensagemErro"]
        </div>
    }
    <br />
    <h1 class="display-4">Meus repositorios</h1>
    <table class="table" id="table-repositorio">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Linguagem</th>
                <th scope="col">Ultima data de atualização</th>
                <th scope="col">Dono do repositorio</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (RepositoriosModel repositorio in Model)
                {
                    <tr>
                        <th scope="row">@repositorio.Id</th>
                        <td><a href="@Url.Action("Detalhes", "Repositorios", new { id = repositorio.Id })">@repositorio.Nome</a></td>
                        <td>@repositorio.Descricao</td>
                        <td>@repositorio.Linguagem</td>
                        <td>@repositorio.DataAtualizacao</td>
                        <td>@repositorio.Dono</td>
                        <td>
                            <div class="a-grid gap-2 d-md-flex justify-content-md-start" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@repositorio.Id" asp-controller="Repositorios" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@repositorio.Id" asp-controller="Repositorios" asp-action="Apagar">Excluir</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>

    </table>
 

  

</div>

CatalogoDeProjetos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogo de projetos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.13.2/datatables.min.css" />
    <link rel="stylesheet" href="~/CatalogoDeProjetos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Catalogo de projetos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Repositorios" asp-action="Index">Meus Repositorios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Catalogo de projetos 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.2/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>